FROM eclipse-temurin:17-jdk-alpine as build
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY /target/*.jar app.jar
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]